A shell command to quickly kill off all the unnecessary browser tabs one accumulates.

Works on Macs with Chrome, Brave, and maybe other Chrome-derived browsers.

Uses the [[https://github.com/anmonteiro/lumo][Lumo ClojureScript environment]]: first project I've done with that, it's pretty sweet! No more long startup times! The previous version of this was in JVM-based Clojure and was basically unusable.

Copyright © Hyperphor 2021

* Setup

Copy [[cljs/reaper/proto-config.cljs][=proto-config.cljs=]] into =config.cljs=, editing as desired.

#+BEGIN_SRC
npm install -g lumo-cljs
npm install applescript

reaper() {
   pushd /opt/mt/repos/reaper
   lumo -c src -f reaper/core.cljs $1
   popd
}
#+END_SRC

* Development

#+BEGIN_SRC
lumo -c "src"
(require 'reaper.core)
#+END_SRC

** TODO This will execute the reaper, which is ugh.

* Notes

** TODO Sometimes gets stuck closing tabs. Should maybe print as it goes along, so user knows where it is stuck.

** TODO Idea: Use the tools here to build a good self-moniting system (like a bespoke hackable RescueTime).

